Revert "to revert"
This reverts commit 59d37e6409da0a0b9a474c760dd2036ec33b9f8a.

diff --git a/.github/workflows/ci-dotnet.yml b/.github/workflows/ci-dotnet.yml
--- a/.github/workflows/ci-dotnet.yml
+++ b/.github/workflows/ci-dotnet.yml
@@ -43,11 +43,92 @@ jobs:
         tools/deployment/initialize-cluster.sh
         tools/deployment/deploy-aio.sh nightly
         
+    - name: Install Protoc
+      uses: arduino/setup-protoc@v3
+
+    - name: Install AvroGen
+      run: (pushd /; dotnet tool install --global Apache.Avro.Tools; popd) # need to install from root to avoid using the nuget.config we for build and push
+  
     - name: Build SDK (Debug)
       run: dotnet build -c Debug dotnet/Azure.Iot.Operations.sln
 
+    - name: Build and Test CodeGen (Debug)
+      run: dotnet build -c Debug codegen/codegen.sln
+
+    - name: CodeGen .NET TestEnvoys
+      run: (cd dotnet/samples/TestEnvoys; ./gen.sh)
+
+    - name: CodeGen StateStore RPC client
+      run: (cd dotnet/src/Azure.Iot.Operations.Services/StateStore; ./gen.sh)
+
+    - name: CodeGen SchemaRegistryEnvoy
+      run: (cd dotnet/src/Azure.Iot.Operations.Services/SchemaRegistry; ./gen.sh)
+
+    - name: Build SDK (Debug)
+      run: dotnet build -c Debug dotnet/Azure.Iot.Operations.sln
+
+    - name: Build SDK (Release)
+      run: dotnet build -c Release dotnet/Azure.Iot.Operations.sln
+
     - name: Deploy HTTP thermostat connector sample
       run: (cd dotnet/samples/HttpThermostatConnectorApp; ./deploy-connector-and-asset.sh)
+
+    - name: Setup Faultable MQTT Broker
+      run: RUNNER_TRACKING_ID="" && dotnet run --project eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/Azure.Iot.Operations.FaultableMqttBroker.csproj &
+
+    - name: Setup SchemaRegistry Host
+      run: RUNNER_TRACKING_ID="" && dotnet run --project eng/test/schema-registry/src/Azure.Iot.Operations.Services.SchemaRegistry.Host/Azure.Iot.Operations.Services.SchemaRegistry.Host.csproj &
+      
+    # This file is created by deploy-aio.sh
+    - name: Load test service account token into environment
+      run: |
+        if [ ! -f ".session/token.txt" ]; then
+          echo "Missing 'token.txt' file"
+          exit 1
+        fi
+
+        echo "TOKEN_FILE_PATH=$(pwd)/.session/token.txt" >> $GITHUB_ENV
+
+    # This file is created by deploy-aio.sh
+    - name: Load CA certificate into environment
+      run: |
+        if [ ! -f ".session/broker-ca.crt" ]; then
+          echo "Missing 'broker-ca.crt' file"
+          exit 1
+        fi
+
+        echo "CA_FILE_PATH=$(pwd)/.session/broker-ca.crt" >> $GITHUB_ENV
+
+    # These files are created by deploy-aio.sh
+    - name: Load client certificates into environment
+      run: |
+        if [ ! -f ".session/client.key" ]; then
+          echo "Missing 'client.key' file"
+          exit 1
+        fi
+
+        if [ ! -f ".session/client.crt" ]; then
+          echo "Missing 'client.crt' file"
+          exit 1
+        fi
+
+        echo "CLIENT_KEY=$(pwd)/.session/client.key" >> $GITHUB_ENV
+        echo "CLIENT_CERT=$(pwd)/.session/client.crt" >> $GITHUB_ENV 
+      
+    - name: Test SDK (TLS + SAT)
+      run: dotnet test dotnet/Azure.Iot.Operations.sln -e MQTT_TEST_BROKER_CS="HostName=127.0.0.1;TcpPort=8884;UseTls=true;CaFile=${{ env.CA_FILE_PATH }};SatAuthFile=${{ env.TOKEN_FILE_PATH }}" -e FAULTABLE_MQTT_TEST_BROKER_CS="HostName=localhost;TcpPort=1884;UseTls=false" --logger:"trx;LogFileName=test-results.trx" -- xunit.parallelizeAssembly=true
+
+    - name: Test SDK (TLS + x509)
+      run: dotnet test dotnet/Azure.Iot.Operations.sln --filter "FullyQualifiedName~Azure.Iot.Operations.Services.IntegrationTests.LeaderElectionClientIntegrationTests.TestFencing" -e MQTT_TEST_BROKER_CS="HostName=127.0.0.1;TcpPort=8883;UseTls=true;CaFile=${{ env.CA_FILE_PATH }};KeyFile=${{ env.CLIENT_KEY }};CertFile=${{ env.CLIENT_CERT }}" --logger:"trx;LogFileName=test-results.trx" -- xunit.parallelizeAssembly=true    
+    
+    - name: Build DSS CLI (Debug)
+      run:  |
+        cd tools/dsscli/src/Azure.Iot.Operations.Services.DssCli
+        dotnet restore
+        dotnet build -c Debug Azure.Iot.Operations.Services.DssCli.csproj
+
+    - name: Build DSS CLI (Release)
+      run: dotnet build -c Release tools/dsscli/src/Azure.Iot.Operations.Services.DssCli/Azure.Iot.Operations.Services.DssCli.csproj
 
     - name: Output Connector App Logs
       run:  |
